title: Universe Crystal
description: Official website of the Universe Crystal Project — a long-term original research project in natural philosophy exploring the nature of the evolving universe as a whole through A Grand View.

theme: jekyll-theme-cayman
